#ifndef _PORTAL_H
#define _PORTAL_H

#define BUTTON_PRIMARY_FIRE 0
#define BUTTON_ALT_FIRE 1
#define BUTTON_MODE_TOGGLE 2
#define BUTTON_RESET 3
#define BUTTON_LONG_RESET 4
#define BUTTON_NONE 5

#endif